baseURL = 'https://netherfoam.github.io/'
languageCode = 'en-us'
title = 'Portfolio & Blog'
author = "Dirk Jamieson"
copyright = "Copyright © 2024, Dirk Jamieson."

theme = "hugo-bearblog"

enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm", "term"]

[params]
  description = "Backend Software Engineer"
  favicon = "/netherfoam.png"
  hideMadeWithLine = true
  avatar = "/profile_picture.jpeg"
